### ISSUE TITLE
请问Mac如何运行程序？

### ISSUE THREAD

**Issue by gray0128** [playGitboy/Json2Csv#1]
感谢作者！

作为非开发人员，想问一下mac系统中如何运行？能否简单说下操作步骤？

**Comment by playGitboy** [comment]
下载Json2Csv.darwin.amd64.tar.gz，终端`tar zxvf Json2Csv.darwin.amd64.tar.gz`解压出主程序"Json2Csv.darwin.amd64"  
终端直接执行主程序即可，比如`./Json2Csv.darwin.amd64  -d data.items  test.json`

注意：高版本MacOS可能提示“无法打开“Json2Csv.darwin.amd64”，因为无法验证开发者”，打开系统偏好设置——安全性与隐私——通用，下面会出现提示点击"仍然允许"按钮后终端运行即可

**Comment by playGitboy** [comment]
下载Json2Csv.darwin.amd64.tar.gz，终端`tar zxvf Json2Csv.darwin.amd64.tar.gz`解压出主程序"Json2Csv.darwin.amd64"  
终端直接执行主程序即可`./Json2Csv.darwin.amd64  -d data.items  test.json`

注意：高版本MacOS可能提示“无法打开“Json2Csv.darwin.amd64”，因为无法验证开发者”，打开系统偏好设置——安全性与隐私——通用，下面会出现提示点击"仍然允许"按钮后重新在终端运行即可

**Comment by gray0128** [comment]
> 下载Json2Csv.darwin.amd64.tar.gz，终端`tar zxvf Json2Csv.darwin.amd64.tar.gz`解压出主程序"Json2Csv.darwin.amd64" 终端直接执行主程序即可，比如`./Json2Csv.darwin.amd64 -d data.items test.json`
> 
> 注意：高版本MacOS可能提示“无法打开“Json2Csv.darwin.amd64”，因为无法验证开发者”，打开系统偏好设置——安全性与隐私——通用，下面会出现提示点击"仍然允许"按钮后终端运行即可

感谢！
