### ISSUE TITLE
json需要转义的话，报错

### ISSUE THREAD

**Issue by x140y40** [playGitboy/Json2Csv#2]
json.json 读取错误： invalid character '\\' looking for beginning of object key string

**Comment by playGitboy** [comment]
实测处理json转义字符没有任何问题  
这个报错应该是json中乱用了不规范字符——单引号导致，标准json中必须且只能用双引号，如果是文本中必须出现单引号根本无须转义如`"name":"test 'this' code"`即可  
参考https://blog.csdn.net/lgysjfs/article/details/86678559

如有其他疑问请提供测试json
